# Generated by Django 4.2.7 on 2023-11-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.RemoveField(
            model_name='advantage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='advantage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
        migrations.AddField(
            model_name='advantage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advantage',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='advantage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
